# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Tinkerer
tagline:          'Ramblings of a tinkerer'
description:      'Tinkerer, Python hobbyist, wanna be automator of all kinds of things!'
url:              https://jrgarrigues.github.io
baseurl:          /

author:
  name:           'John Garrigues'
  url:            https://twitter.com/jrgarrigues

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jrgarrigues

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive'}  # ,'Feed':'/atom.xml'